language: python
dist: xenial

script:
    - pip install twine

after_success:
    - echo [distutils]                                  > ~/.pypirc
    - echo index-servers =                             >> ~/.pypirc
    - echo "  pypi"                                    >> ~/.pypirc
    - echo                                             >> ~/.pypirc
    - echo [pypi]                                      >> ~/.pypirc
    - echo repository=https://upload.pypi.org/legacy/  >> ~/.pypirc
    - echo username=keyi                               >> ~/.pypirc
    - echo password=$PYPI_PASSWORD                     >> ~/.pypirc
    - echo "#!/bin/sh"                                 > ~/deploy.sh
    - echo "python setup.py sdist upload -r pypi"     >> ~/deploy.sh

deploy:
  - provider: script
    script: /bin/sh ~/deploy.sh
    on:
      branch: master
      tags: true
